import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { satoshi } from "@/style/fonts";
import { CartProvider } from "@/components/CartContext"; 


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.className} antialiased`}
      >
        <CartProvider>
          <Header />
            <main>
              {children}
            </main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
